### PR TITLE
Update style

### PR DESCRIPTION
**Pull request by federicobucchi**
Screenshot 2024-10-30 at 2 42 45 PM

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks for the help @federicobucchi!

I'm iffy about the gradient hm... I originally introduced the gradient but then we orange -> yellow -> orange, but then we discussed to make the page to keep the look and feel of the swift.org site with just being white...

Maybe let's keep the just plain page but accept the other css changes?

**Comment by federicobucchi** [comment]
Screenshot 2024-10-30 at 3 16 52 PM

**Comment by ktoso** [comment]
Awesome, thx :)

**Review by ktoso — APPROVED** [review]
Thank you!

**Pull request merged**
